// Traffic Light Controller - Generated by CommandProtocol
// This demonstrates our semantic Arduino command generation

void setup() {
  // Pin configurations and initial state
pinMode(12, OUTPUT);
pinMode(11, OUTPUT);
pinMode(10, OUTPUT);
pinMode(6, OUTPUT);
}

void loop() {
  // Traffic light sequence
digitalWrite(12, HIGH);
digitalWrite(11, LOW);
digitalWrite(10, LOW);
delay(3000);
digitalWrite(11, HIGH);
delay(1000);
digitalWrite(12, LOW);
digitalWrite(11, LOW);
digitalWrite(10, HIGH);
delay(4000);
digitalWrite(10, LOW);
delay(500);
digitalWrite(10, HIGH);
delay(500);
digitalWrite(10, LOW);
delay(500);
digitalWrite(10, HIGH);
delay(500);
digitalWrite(10, LOW);
delay(500);
digitalWrite(10, HIGH);
delay(500);
digitalWrite(10, LOW);
digitalWrite(11, HIGH);
analogWrite(6, 128);
delay(2000);
analogWrite(6, 0);
digitalWrite(11, LOW);
analogWrite(6, 50);
delayMicroseconds(10000);
analogWrite(6, 100);
delayMicroseconds(10000);
analogWrite(6, 200);
delayMicroseconds(10000);
analogWrite(6, 0);
}
